"""empty message

Revision ID: 85fccd589ff6
Revises: e35d52a7c800
Create Date: 2023-05-23 12:26:14.743237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fccd589ff6'
down_revision = 'e35d52a7c800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reaction_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_reaction_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
