"""empty message

Revision ID: 899afdea6ba3
Revises: df5b3d5dd331
Create Date: 2023-05-23 01:07:40.822276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899afdea6ba3'
down_revision = 'df5b3d5dd331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
