"""empty message

Revision ID: e35d52a7c800
Revises: 899afdea6ba3
Create Date: 2023-05-23 12:20:53.557304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35d52a7c800'
down_revision = '899afdea6ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction_type'))
    )
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reaction_type_reaction_type'), 'reaction_type', ['type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reaction_type_reaction_type'), type_='foreignkey')
        batch_op.drop_column('type')

    op.drop_table('reaction_type')
    # ### end Alembic commands ###
